---
# ============================
# MYSQL MASTER
# ============================
- hosts: _Master
  become: yes
  roles:
    - mysql_master

# ============================
# MYSQL SLAVE
# ============================
- hosts: _Slave
  become: yes
  roles:
    - mysql_slave

# ============================
# MYSQL CLIENT
# ============================
- hosts: _Client
  become: yes
  roles:
    - mysql_client
