---
- name: Show master/slave IPs
  debug:
    msg:
      - "Master: {{ groups['Role_Master'][0] }}"
      - "Slave: {{ groups['Role_Slave'][0] }}"

- name: Install MySQL client
  apt:
    name:
      - mysql-client
      - python3-pymysql
    state: present

- name: Test connection to master
  shell: mysql -h {{ groups['Role_Master'][0] }} -u root -p{{ mysql_root_password }} -e "SHOW DATABASES;"
  register: master_test
  ignore_errors: yes

- name: Test connection to slave
  shell: mysql -h {{ groups['Role_Slave'][0] }} -u root -p{{ mysql_root_password }} -e "SHOW DATABASES;"
  register: slave_test
  ignore_errors: yes
